### ISSUE TITLE
단어 추가 - 부사:되도록이면

### ISSUE THREAD

**Issue by Taurean75** [spellcheck-ko/hunspell-dict-ko#21]
부사: 되도록이면

**Comment by changwoo** [comment]
"되도록"까지는 단어 추가하면 되는데, "되도록이면"은 사전에도 없고, 분석도 못 하겠지만 쓰는 말이네요.  부산대는 틀린 말, 네이버/다음은 맞는 말로 취급합니다. 추가하는 방향으로 가지요.

https://galkwi.pyok.org/entry/31777/
