### ISSUE TITLE
한글 자모 분리 현상

### ISSUE THREAD

**Issue by Zeta611** [spellcheck-ko/hunspell-dict-ko#24]
간단하게 맞춤법 검사를 위한 파일 `test.txt`를 만들고 `hunspell test.txt`를 실행시키면 자모가 분리된 단어들이 뜹니다.
실제로 수정한 파일에도 자모가 분리되어서 들어갑니다.

macOS Sierra에서 Hunspell 1.6.0를 구동하고 있습니다.

![2017-02-27 8 44 40](https://cloud.githubusercontent.com/assets/9553691/23360258/b9ad04fe-fd2d-11e6-972b-22e3b2b854a2.png)

**Comment by changwoo** [comment]
hunspell 문제 같군요. OCONV (내부 인코딩에서 변환) 적용을 안 하면 이렇게 됩니다.

**Comment by Zeta611** [comment]
@changwoo 어떻게 해결해야 하나요?

**Comment by changwoo** [comment]
이 프로젝트에서 해결할 수 있는 건 없습니다. hunspell 콘솔 프로그램의 버그예요. API 단계에서는 OCONV 적용이 잘 되는 것으로 보이니 잘 동작하지만요.

**Comment by changwoo** [comment]
참고로 이런 이슈가 있습니다. 다른 부분에서 OCONV 적용 안 되는 얘기이긴 하지만요.

https://github.com/hunspell/hunspell/issues/88

**Comment by changwoo** [comment]
종성만 분리되는 걸 보고 기존 문제가 표시만 저렇게 된다고 생각했는데 다른 종류의 문제군요.

이 문제는 hunspell 1.6.0 버그로 리포트했습니다. 역시 hunspell이 해결되야 합니다.

https://github.com/hunspell/hunspell/issues/480

**Comment by changwoo** [comment]
master branch에서 수정 사항이 적용되었습니다. 해결되었습니다. 다음 릴리스를 기다리세요. 

https://github.com/hunspell/hunspell/pull/481

**Comment by Zeta611** [comment]
아 감사합니다!
