### ISSUE TITLE
dic / aff 크기 및 제시어 실행 시간 문제 문의

### ISSUE THREAD

**Issue by kwonoj** [spellcheck-ko/hunspell-dict-ko#30]
안녕하세요, 먼저 사전 업데이트에 늘 감사드립니다. 

이전까지 저는 비교적 예전 버전의 사전을 사용하고 있었습니다. 구체적으로는 chromium 소스 트리에 포함되어 있는 bdic (https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/+/master/ko-3-0.bdic) 과 같은 버전의 사전을 사용하고 있던 중에, 근래 업데이트된 최근 버전 0.6.4를 시험하고 있는 중입니다. 

최신 버전의 사전에서 몇몇 단어의 제시어를 가져올 때 이전 버전보다 확연할 정도로 속도 차이가 발생하는 것을 발견할 수 있었는데, 이를테면 `한녕하세요`와 같은 단어의 제시어를 가져올 때 0.6.1버전의 경우 약 300-350ms가 걸리는 반면 최근 버전의 경우 평균 950ms정도가 걸리고 있습니다. (실제 수행 시간의 경우 시스템 환경에 따라 상이) 단순한 추측으로는 0.6.1버전 이후 dic / aff 모두 크기가 거의 두 배 가까이 커진 것과 관계가 있지 않을까 싶습니다만 정확한 원인은 찾을 수 없었습니다.

현재 저는 데스크탑 기반의 어플리케이션의 컨텍스트 메뉴에 제시어를 표시하고 있어 (아래와 같은 경우를 생각하시면 됩니다) 실행 시간의 증가는 다소 부담이 되는 상황입니다.
![image](https://user-images.githubusercontent.com/1210596/31058236-3aa261aa-a6a5-11e7-8dd2-9accb1250137.png)

이 문제를 해결할 수 있는 방법이 있을지요? 
감사합니다.

**Comment by changwoo** [comment]
0.6.1 뒤에 용언 활용, 특히 선어말어미 형태가 몇 개 추가되면서 크기가 커진 것과 관계가 있습니다. suffixdata.py에서 선어말어미 선언을 줄이거나 단순화하면 크기나 속도는 많이 좋아지지만 그러면 커버하지 못하는 어미가 많아지겠죠. 현재 hunspell의 기능 제약에서 한국어 용언 활용 구현 수준을 너무 높이면 크기/속도가 문제가 되고, 크기/속도만 생각하자면 구현하지 못하는 용언 활용이 많아지고 그런 관계에 있습니다. 

잘 알고 있고 아직까지는 참을 만한 수준이라고 생각하고 있는데 염두에 두고는 있습니다.

**Comment by kwonoj** [comment]
@changwoo 상세한 설명 감사드립니다.
