### ISSUE TITLE
0.6.4 버전 오류가 발생합니다. error: line 22471: bad entry number

### ISSUE THREAD

**Issue by soulawaker** [spellcheck-ko/hunspell-dict-ko#33]
안녕하세요.

ubuntu 16.04 기반 elementary os loki에 spacemacs를 사용 중인 유저입니다.

우분투 리파지터리에서 hunspell 1.3.3 버전과 hunspell-dict-ko 0.5.6를 설치하여 사용하다가

오늘 이곳 깃헙 release의 `ko-aff-dic-0.6.4.zip`을 내려받아

ko.aff와 ko.dic만 기존의 /usr/share/hunspell 내부의 데이터와 교체하여 사용해보았습니다.

이후 hunspell -D를 시도하니 

error: line 22471: bad entry number 메시지가 중간에 뜹니다.

동작은 하는 것으로 보이는데 에러 메시지를 보게 되어 알려드립니다.

**Comment by changwoo** [comment]
"AM 0" 이거 같은데요. 어차피 지금 안 쓰는 부분이라서 상관없을 것 같기는 한데 hunspell 버전별로 차이가 있는 것 같으니 막아놓겠습니다.
