### ISSUE TITLE
따옴표 등의 문장부호 질문드립니다.

### ISSUE THREAD

**Issue by youlive789** [spellcheck-ko/hunspell-dict-ko#46]
hunspell을 설치하고 사전을 ko.aff, ko.dic으로 업데이트한 상황입니다.

테스트로 틀린 문장부호 위치를 잡을 수 있나 확인해봤는데 잡을 수 없는 것 같습니다.

예를 들어 ""안녕하세요?" 같은 문장의 경우 앞에 따옴표가 연속적으로 붙어서 틀린문장인데

검출이 안되어 질문드립니다.

**Comment by changwoo** [comment]
그건 못 합니다. 보통 앱 수준에서 문장 부호 뺀 단어 단위로 분리한 다음 hunspell로 넘어오게 되어 있습니다.

**Comment by youlive789** [comment]
답변 감사드립니다!

**Comment by youlive789** [comment]
> 그건 못 합니다. 보통 앱 수준에서 문장 부호 뺀 단어 단위로 분리한 다음 hunspell로 넘어오게 되어 있습니다.

답변 감사드립니다!
