### ISSUE TITLE
qwebengine_convert_dict 도구를 사용하여 qtwebengine 사전으로 변환 시도 시 에러

### ISSUE THREAD

**Issue by OctopusET** [spellcheck-ko/hunspell-dict-ko#50]
`Word does not match!
  Index:    13975
  Expected: 김수한무거북이와두루미삼천갑자동방삭치치카포사리사리센타워리워리세브리캉무드셀라구름위허리케인에담벼락서생원에고양이고양이는바둑이바둑이는돌돌이
  Actual:   김수한무거북이와두루미삼천갑자동방�
ERROR converting, the dictionary does not check out OK.`

qtwebengine 사전으로 변환을 시도하였으나, 위와 같은 오류로 인해 변환이 불가능 합니다. 

관련 이슈:
https://github.com/wooorm/dictionaries/issues/14

**Comment by changwoo** [comment]
다음에 써 있듯이 "김수한무..."는 장난으로 넣어놓은 단어입니다. 너무 길어서 그런 것 같은데 이 단어 삭제하고 변환해 보시죠.  아마 말씀하신 변환 툴에 길이 제한이 있는 것 같군요.

https://github.com/spellcheck-ko/hunspell-dict-ko/blob/master/dict-ko-builtins.yaml#L208

이 프로젝트의 문제가 아니므로 이 이슈는 닫겠습니다.

**Comment by OctopusET** [comment]
그부분을 삭제하니 바로 되는 군요 그쪽 툴에 이슈를 올려야 겠습니다.
확인 해주셔서 감사합니다.
