### ISSUE TITLE
영어 검사 비활성화 문제

### ISSUE THREAD

**Issue by tmvkrpxl0** [spellcheck-ko/hunspell-dict-ko#51]
KDE Neon 유저입니다. hunspell-ko 0.7.92-1 을 사용하고 있고 hunspell 은 1.7.0 입니다.

Kate 랑 Intellij Idea 를 사용하면서 발견한 문제인데, 한글 dictionary 파일을 사용하도록 하면 모든 영어 검사가 비활성화 되는 것 같습니다.
Kate에서 영어를 기본 맞춤법 검사 언어로 설정할 시:
![image](https://user-images.githubusercontent.com/41675181/226567353-8d0be4df-9004-4e9c-8973-966bf77fe8af.png)
![image](https://user-images.githubusercontent.com/41675181/226567423-ccc08222-5f8e-43d6-8d8a-0f767634ebaa.png)
 
 Kate에서 한글을 기본 맞춤법 검사 언어로 설정할 시:
![image](https://user-images.githubusercontent.com/41675181/226567697-4ac5a831-203c-4ad5-8e45-44ff35c8b404.png)
![image](https://user-images.githubusercontent.com/41675181/226567566-20a62c88-7945-4456-8bfd-5a90166d6448.png)

또한 Intellij 에서는 ko.dict 파일을 추가하는 순간 모든 맞춤법 검사가 비활성화 됩니다.
ko.dict 없이:
![image](https://user-images.githubusercontent.com/41675181/226567886-96f18bdb-e0b7-4ac9-a38d-db5cc2cb93c4.png)

ko.dict 추가 이후:
![image](https://user-images.githubusercontent.com/41675181/226568120-78f01093-3c23-4777-b5d8-ddfb3fadd925.png)
![image](https://user-images.githubusercontent.com/41675181/226568307-593d3194-8611-4156-ade4-26a3faf273fd.png)

**Comment by changwoo** [comment]
겪고 계신 문제는 이 프로젝트의 범위라고 볼 수 없습니다. 이 프로젝트는 주어진 텍스트를 맞춤법 검사하는 한국어 사전이고, 텍스트에서 어떤 부분을 어떤 언어의 사전으로 검사할지는 각 애플리케이션에서 결정하는 문제라서 제가 고칠 수 없는 문제입니다.  그럼에도 불구하고 알파벳으로 구성된 단어가 이 사전에 입력된다면 맞는 단어로 취급하는 것은 사실입니다만, 한국어 맞춤법 검사를 해야 하는 상황에 애플리케이션에서 영문자를 입력했을 때 이렇게 취급하는 게 한국어 사전으로서는 최선입니다. LibreOffice와 같은 경우는 애플리케이션에서 언어를 구분해서 각각 다른 사전에 맞춤법 검사를 하는 식으로 동작합니다.

스크린샷을 보고 판단하기에는 Kate의 경우에는 모든 텍스트를 단일 언어로 처리하는 것으로 보이며, 그에 따른 근본적인 한계가 있지만 작성된 대로 동작하는 것처럼 보입니다.

IJ에서는 언어 설정과 무관하게 한글 텍스트를 맞춤법 검사에서 제외하고 영문 텍스트만 검사 대상으로 삼는 것처럼 보이는군요.
