### ISSUE TITLE
M2 Silicon 맥에서 제대로 작동하지 않습니다. 

### ISSUE THREAD

**Issue by arecibo** [spellcheck-ko/hunspell-dict-ko#52]
M2 Silicon (OS는 Ventura 13.2.1) 에 hunspell 1.7.2 를 homebrew를 이용해서 설치했습니다.

영어나 일본어 문서는 모두 오탈자를 잘 걸러내는데, 한글 문서만 되지 않네요.

ko.dic 와 ko.aff 를 각각 ko_KR.dic 와 ko_KR.aff 로도 이름 변경을 해보기도 했는데, 여전히 오탈자가 있는 단어들을 골라내지 못합니다. 

(소스를 컴파일해도 마찬가지 문제가 발생합니다.)

어떻게 하면 해결할 수 있을까요?

[en.txt](https://github.com/spellcheck-ko/hunspell-dict-ko/files/11289058/en.txt)
[ko.txt](https://github.com/spellcheck-ko/hunspell-dict-ko/files/11289059/ko.txt)
[jp.txt](https://github.com/spellcheck-ko/hunspell-dict-ko/files/11289060/jp.txt)
![hunspell-ko-problem](https://user-images.githubusercontent.com/13296840/233447392-a885b0d9-5b4a-4236-be70-58cd75fb0365.png)
![dictionary-list](https://user-images.githubusercontent.com/13296840/233448024-bc991438-25d9-4114-8d91-c319234debd9.png)

**Comment by changwoo** [comment]
homebrew에 들어 있는 hunspell이 저 위치를 못 읽는 것 아닐까요? hunspell -D 명령으로 ko_KR 사전이 제대로 들어갔는지 확인해 보세요.

**Comment by arecibo** [comment]
hunspell -D 를 넣었을 때 ko_KR과 ko 사전 모두 잘 등록되어 있습니다.

**Comment by arecibo** [comment]
homebrew에 등록된 hunspell 이 제대로 작동하지 않네요. 
기존 homebrew로 설치된 hunspell을 삭제하고 나서, 
hunspell-1.7.2 source를 받아서 컴파일을 하고 설치를 하고 나니 제대로 작동하네요.

**Comment by changwoo** [comment]
다른 프로젝트 (homebrew hunspell) 버그로 판단되어 닫습니다.
