### ISSUE TITLE
단어를 추가했을 때

### ISSUE THREAD

**Issue by arecibo** [spellcheck-ko/hunspell-dict-ko#53]
안녕하세요?

hunspell을 통해 문서의 맞춤법을 검사할 때, 사전에 올라있지 않은 단어들일 경우 제가 추가하여 ~/.hunspell_ko_KR에 등록이 되고 있습니다.

그런데, 추가된 단어들에 조사가 붙을 경우 조사가 붙는 경우에 새로운 단어로 인식을 하고 있습니다. 
(제 분야에서는 복합명사가 많이 쓰이는, 이런 복합명사에는 띄어쓰기를 하지 않는 경우가 많아서, hunspell에서 띄어쓰기를 제안하더라도 새로운 단어로 등록하는 편입니다.)

이 문제가 이미 해결이 되었는데 제가 기능을 모르는 것인지, 아니면 원래 이런 것인지 궁금합니다.
아니면 제가 할 수 있는 해결책이 있는지도 궁금하구요.

issue는 아니지만, hunspell-dict-ko 를 쓰다가 의문이 들어서 글을 남깁니다.

**Comment by changwoo** [comment]
품사 정보 없이 추가만 하면 조사와 결합되지 않습니다. 

0.7.92 기준으로는 "추가단어/25" 식으로 25를 붙이면 일반 명사처럼 동작할 겁니다. 이 번호는 빌드할 때 결정되기 때문에 버전업이 됐을 때 달라질 가능성이 있구요. 사전 정의할 때 기본값 품사 같은 기능이 있으면 좋겠는데 그런 건 없네요.
