### ISSUE TITLE
bdic 파일로 컴파일 할 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by somehowko** [spellcheck-ko/hunspell-dict-ko#58]
dic aff를 bdic 파일로 컴파일 할 수 있는 방법이 있을까요?

**Comment by OctopusET** [comment]
qwebengine_convert_dict 를 사용해 보세요

https://doc.qt.io/qt-6/qtwebengine-webenginewidgets-spellchecker-example.html
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hunspell-ko#n40

**Comment by somehowko** [comment]
감사합니다. 해결되었습니다.

궁금한점이 있는데 해당 파일과 파이어폭스에서 쓰는 사전이 다른 것 같습니다. 

'사람들은' 을 오류라고 판단한다거나 이 버전에서는 띄어쓰기의  경우 제안이 거의 노출되지 않거나 하는 식으로요.
 
혹시 수정 방법이 있을까요? 


***

**Comment by OctopusET** [comment]
해당 파일은 정확히 어떤 파일을 말씀하시는 걸까요?
그리고 사용하시는 파이어폭스 버전 및 추가적인 시스템 환경을 병기하여 새로운 issue를 열어주셔도 좋을 것 같습니다.

**Comment by somehowko** [comment]
헛, 새로운 이슈를 열었습니다. 
혹시나 저처럼 코딩과 프로그램에 익숙하지 않으신 분들을 위해, 

qt creator 설치 후, 설치 경로에서 qwebengine_convert_dict 를 찾아 cmd로 실행하시면 쉽게 변환하실 수 있습니다.
다른 방법으로는 윈도우 terminal 에 우분투를 설치해서 리눅스 환경에서 변환하는 방법도 있습니다.
(https://github.com/jankelemen/convert-dict-tool-from-chromium 참고)
