### ISSUE TITLE
파이어폭스 사전 관련 문의

### ISSUE THREAD

**Issue by somehowko** [spellcheck-ko/hunspell-dict-ko#59]
0.7.94 버전 사전 파일을 이용한 결과값과 
파이어폭스 117.0.1 버전에서 사용하는 huspell 사전을 이용한 결과값이 다릅니다.

(애드온 버전 0.7.1-2.1webext  // https://addons.mozilla.org/en-US/firefox/addon/korean-spellchecker/)

지금 생각해보니, bdic로 만드는 과정에서 문제가 있지 않았나 싶습니다.

파이어폭스에서 사용하고 있는 aff와 dic를 추출해 bdic 로 변환해 확인해보고 싶어도 단어가 일치하지 않아 실패하고 있습니다.

(Word doesn't match)

**Comment by changwoo** [comment]
다른 버전의 사전을 기초로 만든 것이므로 당연히 결과는 다릅니다. (이 프로젝트에서는 애드온 릴리스를 관리하지 않습니다.)

또 hunspell 사전에서는 단어가 주어졌을 때 맞춤법을 검사할 뿐 어떻게 단어를 잘라서 언어별로 검사할지는 각 앱에서 결정합니다. 그래서 파이어폭스가 단어를 구분하는 방법이 다르면 그것 때문에 다를 수 있구요.
